# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias ppon='export http_proxy=http://s1.liaoxingyi.com:8118;export https_proxy=http://s1.liaoxingyi.com:8118;echo "proxy on"'
alias pon='export http_proxy=http://127.0.0.1:8118;export https_proxy=http://127.0.0.1:8118;echo "proxy on"'
alias poff='export http_proxy=; export https_proxy=;echo "proxy off"'
