config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_ankdown-conf.yaml:
    dst: ~/.ankdown-conf.yaml
    src: ankdown-conf.yaml
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  d_powerline:
    src: config/powerline
    dst: ~/.config/powerline
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_ripgreprc:
    src: ripgreprc
    dst: ~/.ripgreprc
  f_hmscreens:
    src: bin/hmscreens
    dst: ~/bin/hmscreens
  f_smp.py:
    src: bin/smp.py
    dst: ~/bin/smp.py
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_pip.conf:
    src: pip/pip.conf
    dst: ~/.pip/pip.conf
  f_dpo:
    src: bin/dpo
    dst: ~/bin/dpo
  f_tmux-session-playground.yaml:
    src: tmux-session-playground.yaml
    dst: ~/.tmux-session-playground.yaml
  f_tmux-session-work.yaml:
    src: tmux-session-work.yaml
    dst: ~/.tmux-session-work.yaml
  f_flake8:
    src: config/flake8
    dst: ~/.config/flake8
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_functions:
    src: config/fish/functions
    dst: ~/.config/fish/functions
  f_global_ignore:
    src: global_ignore
    dst: ~/.global_ignore
  f_ctags:
    src: ctags
    dst: ~/.ctags
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  f_fish_variables:
    src: config/fish/fish_variables
    dst: ~/.config/fish/fish_variables
  d_colorschemes:
    src: config/powerline/colorschemes
    dst: ~/.config/powerline/colorschemes
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
profiles:
  localhost:
    dotfiles:
    - f_tmux.conf
    - f_config.fish
    - d_functions
    - f_global_ignore
    - f_ctags
    - f_ankdown-conf.yaml
    - d_powerline
    - f_init.vim
    - f_ripgreprc
    - f_hmscreens
    - f_smp.py
    - f_gitconfig
    - f_dpo
    - f_tmux-session-playground.yaml
    - f_tmux-session-work.yaml
    - f_flake8
    - f_vimrc
    - f_coc-settings.json
    - f_fish_variables
    - d_colorschemes
    - d_ranger
  balrog2:
    dotfiles:
    - f_bashrc
    - f_bash_profile
  server:
    dotfiles:
    - f_bashrc
