config:
  backup: true
  create: true
  dotpath: dotfiles
  minversion: 1.14.0
dotfiles:
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  d_powerline:
    src: config/powerline
    dst: ~/.config/powerline
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_ripgreprc:
    src: ripgreprc
    dst: ~/.ripgreprc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_pip.conf:
    src: pip/pip.conf
    dst: ~/.pip/pip.conf
  f_tmux-session-playground.yaml:
    src: tmux-session-playground.yaml
    dst: ~/.tmux-session-playground.yaml
  f_tmux-session-work.yaml:
    src: tmux-session-work.yaml
    dst: ~/.tmux-session-work.yaml
  f_flake8:
    src: config/flake8
    dst: ~/.config/flake8
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_global_ignore:
    src: global_ignore
    dst: ~/.global_ignore
  f_ctags:
    src: ctags
    dst: ~/.ctags
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  d_colorschemes:
    src: config/powerline/colorschemes
    dst: ~/.config/powerline/colorschemes
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_general:
    src: config/nvim/general
    dst: ~/.config/nvim/general
  d_plug-config:
    src: config/nvim/plug-config
    dst: ~/.config/nvim/plug-config
  d_vim-plug:
    src: config/nvim/vim-plug
    dst: ~/.config/nvim/vim-plug
  d_snips:
    src: config/nvim/snips
    dst: ~/.config/nvim/snips
  d_themes:
    src: config/nvim/themes
    dst: ~/.config/nvim/themes
    chmod: '755'
  f_pon.fish:
    src: config/fish/functions/pon.fish
    dst: ~/.config/fish/functions/pon.fish
  f_poff.fish:
    src: config/fish/functions/poff.fish
    dst: ~/.config/fish/functions/poff.fish
  f_don.fish:
    src: config/fish/functions/don.fish
    dst: ~/.config/fish/functions/don.fish
  f_doff.fish:
    src: config/fish/functions/doff.fish
    dst: ~/.config/fish/functions/doff.fish
profiles:
  mbp:
    dotfiles:
    - f_tmux.conf
    - f_config.fish
    - f_global_ignore
    - f_ctags
    - d_powerline
    - f_init.vim
    - f_ripgreprc
    - f_gitconfig
    - f_tmux-session-playground.yaml
    - f_tmux-session-work.yaml
    - f_flake8
    - f_coc-settings.json
    - d_colorschemes
    - d_ranger
    - d_general
    - d_plug-config
    - d_vim-plug
    - d_snips
    - d_themes
    - f_pon.fish
    - f_poff.fish
    - f_don.fish
    - f_doff.fish
    - d_ranger
    - f_config
